[phases.setup]
nixPkgs = ["nginx", "php", "supervisor"]

[phases.build]
cmds = [
    "mkdir -p /app",
    "cp /etc/nginx/fastcgi_params /app/fastcgi_params"
]

[phases.start]
cmds = ["supervisord -c /app/supervisord.conf"]
